import { useState } from 'react';
import { Bell, BookOpen, BriefcaseBusiness, Bus, CalendarDays, ChevronDown, CircleDollarSign, FileText, GraduationCap, LayoutDashboard, Library, LogOut, Menu, Newspaper, Package, Search, Settings, ShieldCheck, Users, X } from 'lucide-react';
import LanguageSwitcher from './LanguageSwitcher';

const itemMap = [
  ['add-department', 'addDepartment', BriefcaseBusiness],
  ['overview', 'overview', LayoutDashboard], ['students', 'students', GraduationCap], ['admissions', 'admissions', Users], ['academics', 'academics', BookOpen], ['attendance', 'attendance', CalendarDays], ['finance', 'finance', CircleDollarSign], ['library', 'library', Library], ['transport', 'transport', Bus], ['inventory', 'inventory', Package], ['news', 'news', Newspaper], ['notices', 'notices', Bell], ['documents', 'documents', FileText], ['timetable', 'timetable', CalendarDays], ['teachers', 'teachers', Users], ['reports', 'reports', FileText], ['homework', 'academics', BookOpen], ['feeding', 'inventory', Package], ['expenses', 'finance', CircleDollarSign], ['assets', 'inventory', Package], ['loans', 'library', Library],
];
const roleItems = { admin: itemMap.map(([id]) => id), dos: ['overview', 'students', 'admissions', 'academics', 'attendance', 'news', 'notices', 'documents', 'timetable', 'teachers', 'reports'], teacher: ['overview', 'students', 'academics', 'attendance', 'notices', 'timetable', 'homework', 'reports'], parent: ['overview', 'attendance', 'finance', 'academics', 'library', 'transport', 'notices', 'reports', 'homework', 'feeding'], accountant: ['overview', 'students', 'finance', 'transport', 'inventory', 'expenses', 'assets'], librarian: ['overview', 'students', 'library', 'loans'], student: ['overview', 'academics', 'attendance', 'finance', 'library', 'transport', 'notices', 'reports', 'homework'] };

export default function AppShell({ t, language, onLanguageChange, user, activePage, onNavigate, onLogout, children }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const available = roleItems[user?.role] || roleItems.admin;
  const navItems = itemMap.filter(([id]) => available.includes(id));
  const labelById = Object.fromEntries(itemMap.map(([id, key]) => [id, id === 'add-department' ? 'Add Department' : (t[key] || id)]));
  return (
    <div className="min-h-screen bg-[#f4f8f9] text-slate-800">
      {mobileOpen && <button aria-label="Close navigation" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-30 bg-slate-900/40 lg:hidden" />}
      <aside className={`fixed inset-y-0 left-0 z-40 flex w-[264px] flex-col border-r border-slate-200 bg-white px-4 py-6 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex items-center gap-3 px-2"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#1d7b91] text-white shadow-lg shadow-cyan-900/10"><ShieldCheck size={22} /></div><div className="min-w-0"><strong className="block font-display text-sm font-bold text-slate-800">Forever King</strong><span className="block text-[9px] font-bold tracking-[0.18em] text-slate-400">ACADEMY · FKAMS</span></div><button className="ml-auto text-slate-400 lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close"><X size={18} /></button></div>
        <div className="mt-8 flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-cyan-100 text-xs font-extrabold text-cyan-800">FK</div><div className="min-w-0 flex-1"><b className="block truncate text-[11px]">Forever King Academy</b><span className="block text-[10px] text-slate-400">2025 / 2026 · Term 2</span></div><ChevronDown size={15} className="text-slate-400" /></div>
        <p className="mb-2 mt-8 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Workspace</p>
        <nav className="space-y-1">{navItems.map(([id, key, Icon]) => <button key={id} onClick={() => { onNavigate(id); setMobileOpen(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs font-semibold transition ${activePage === id ? 'bg-cyan-50 text-cyan-800' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800'}`}><Icon size={17} className={activePage === id ? 'text-cyan-700' : 'text-slate-400'} /><span>{labelById[id]}</span>{id === 'students' && <span className="ml-auto rounded-full bg-cyan-100 px-2 py-0.5 text-[10px] text-cyan-700">150</span>}</button>)}</nav>
        <div className="mt-auto border-t border-slate-100 pt-4"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-xs font-semibold text-slate-500 hover:bg-slate-50"><Settings size={17} className="text-slate-400" />{t.settings}</button><div className="mt-4 flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-full bg-amber-100 text-[10px] font-extrabold text-amber-800">{user?.name?.slice(0, 2).toUpperCase() || 'FK'}</div><div className="min-w-0 flex-1"><b className="block truncate text-[11px]">{user?.name || 'FKAMS User'}</b><span className="block text-[10px] capitalize text-slate-400">{user?.role || 'admin'}</span></div></div><button onClick={onLogout} title={t.logout} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-rose-200 px-3 py-2.5 text-xs font-bold text-rose-600 hover:bg-rose-50"><LogOut size={16} />Log out</button></div>
      </aside>
      <main className="lg:pl-[264px]"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-slate-200/80 bg-white/90 px-5 backdrop-blur-md sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileOpen(true)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 lg:hidden" aria-label="Open navigation"><Menu size={21} /></button><div className="hidden items-center gap-2 text-xs sm:flex"><span className="text-slate-400">{t.dashboard}</span><span className="text-slate-300">/</span><b className="capitalize text-slate-600">{labelById[activePage] || activePage}</b></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-slate-400 md:flex"><Search size={16} /><input className="w-40 bg-transparent text-xs outline-none placeholder:text-slate-400" placeholder={t.search} /></div><LanguageSwitcher language={language} onChange={onLanguageChange} label={t.language} /><button className="relative rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label={t.notices}><Bell size={18} /><i className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-rose-400" /></button></div></header><div className="mx-auto flex h-[calc(100vh-72px)] min-h-0 max-w-[1440px] flex-col overflow-y-auto px-5 py-7 [scrollbar-width:thin] [scrollbar-color:#94a3b8_transparent] sm:px-8 sm:py-10"><div className="flex-1">{children}</div><footer className="mt-12 border-t border-slate-200 pt-6 text-xs text-slate-400"><div className="flex flex-col justify-between gap-2 sm:flex-row"><span>Forever King Academy · FKAMS</span><span>Secure school management workspace · © 2026</span></div></footer></div></main>
    </div>
  );
}
