import { useState } from 'react';
import { CheckCircle2, GraduationCap, UserPlus } from 'lucide-react';
import api from '../lib/api';

const initial = { fullName: '', username: '', email: '', admissionNumber: '', className: '', parentPhone: '', gender: 'female', birthday: '', academicYear: '2025/2026', password: '', repassword: '', subjectOrModule: '', diplomaKey: '', resultSlipKey: '' };
export default function RegistrationPage({ onBack }) {
  const [type, setType] = useState('student'); const [form, setForm] = useState(initial); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); if (form.password !== form.repassword) return setError('Passwords do not match.'); try { const endpoint = type === 'student' ? '/students' : '/teachers/register'; const { data } = await api.post(endpoint, form); setMessage(`${data.message} ${data.username ? `Username: ${data.username}` : ''}`); setForm(initial); } catch (requestError) { setError(requestError.response?.data?.error || 'Unable to register record.'); } };
  return <div className="mx-auto max-w-4xl space-y-6"><button onClick={onBack} className="text-xs font-bold text-cyan-700">← Back to dashboard</button><section className="rounded-3xl bg-[#17333d] p-6 text-white sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200">DOS registration</p><h1 className="mt-2 font-display text-2xl font-bold">Register a student or teacher</h1><p className="mt-2 text-sm text-slate-300">QR codes are generated automatically. DOS controls all records after registration.</p></section><div className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm"><button onClick={() => setType('student')} className={`flex flex-1 items-center justify-center gap-2 rounded-xl px-3 py-3 text-xs font-bold ${type === 'student' ? 'bg-cyan-700 text-white' : 'text-slate-500'}`}><GraduationCap size={16} /> Student</button><button onClick={() => setType('teacher')} className={`flex flex-1 items-center justify-center gap-2 rounded-xl px-3 py-3 text-xs font-bold ${type === 'teacher' ? 'bg-cyan-700 text-white' : 'text-slate-500'}`}><UserPlus size={16} /> Teacher</button></div>{message && <div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-xs text-emerald-700"><CheckCircle2 size={16} />{message}</div>}{error && <div className="rounded-xl bg-rose-50 px-4 py-3 text-xs text-rose-700">{error}</div>}<form onSubmit={submit} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-7">{field('Full name', 'fullName', form, update, true)}{type === 'teacher' ? field('Email', 'email', form, update, true, 'email') : field('Admission number', 'admissionNumber', form, update, true)}{type === 'student' && field('Class', 'className', form, update, true)}{field('Username (optional)', 'username', form, update)}{field('Birthday', 'birthday', form, update, true, 'date')}<label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">Gender</span><select value={form.gender} onChange={update('gender')} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-xs outline-none"><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option></select></label>{type === 'student' ? field('Parent phone', 'parentPhone', form, update, true) : field('Subject or module', 'subjectOrModule', form, update, true)}{field('Academic year', 'academicYear', form, update, true)}{field('Password', 'password', form, update, true, 'password')}{field('Re-enter password', 'repassword', form, update, true, 'password')}{type === 'student' ? field('Result slip storage key (optional)', 'resultSlipKey', form, update) : field('Diploma storage key (optional)', 'diplomaKey', form, update)}<button className="flex items-center justify-center gap-2 rounded-xl bg-[#1d7b91] px-4 py-3 text-xs font-bold text-white sm:col-span-2"><UserPlus size={16} /> Register {type}</button></form></div>;
}
function field(label, key, form, update, required = false, type = 'text') { return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span><input required={required} type={type} value={form[key]} onChange={update(key)} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-xs outline-none focus:border-cyan-600" /></label>; }
