import { useEffect, useState } from 'react';
import { Activity, Award, BookOpen, Bus, CalendarDays, CheckCircle2, CircleDollarSign, ClipboardCheck, FileText, Library, MessageSquare, Package, QrCode, School, ShieldCheck, UserCheck, Users, Utensils, WalletCards } from 'lucide-react';
import ActionCard from '../components/ActionCard';
import DataTable from '../components/DataTable';
import StatCard from '../components/StatCard';
import api from '../lib/api';

const roleCopy = {
  admin: { title: 'Administration centre', description: 'Full visibility across academic, financial and operational work.', actions: [['Documents', FileText, 'Manage contracts, certificates and policies.', 'documents', 'violet'], ['School dashboard', Activity, 'Review the complete school pulse.', 'overview', 'cyan'], ['User access', ShieldCheck, 'Manage roles, accounts and security.', 'students', 'emerald']] },
  dos: { title: 'Director of studies workspace', description: 'Make decisions, approve applications and keep the academy moving.', actions: [['Class & subject management', School, 'Create classes, subjects and teacher assignments.', 'class-management', 'cyan'], ['Review admissions', UserCheck, 'Approve students and teachers with comments.', 'admissions', 'amber'], ['Register records', Users, 'Register students who did not apply and new teachers.', 'registration', 'cyan'], ['Timetable', CalendarDays, 'Build classes, rooms and teacher schedules.', 'timetable', 'cyan'], ['Teacher management', Users, 'Contracts, attendance, payroll and assignments.', 'teachers', 'violet'], ['Student reports', Award, 'Prepare complete report cards and rankings.', 'reports', 'emerald'], ['School notices', MessageSquare, 'Publish updates for the community.', 'notices', 'rose']] },
  teacher: { title: 'Teacher workspace', description: 'Everything you need for your classes, assessments and daily teaching.', actions: [['My students', Users, 'Only students in your assigned classes.', 'students', 'cyan'], ['Take attendance', ClipboardCheck, 'Mark present, absent or late.', 'attendance', 'emerald'], ['Create assessment', BookOpen, 'Choice, fill and match tests with a timer.', 'academics', 'violet'], ['Homework', FileText, 'Publish work and track due dates.', 'homework', 'amber'], ['My timetable', CalendarDays, 'See your classes and rooms.', 'timetable', 'cyan'], ['Submit report', MessageSquare, 'Send academic updates to DOS.', 'reports', 'rose']] },
  student: { title: 'Student portal', description: 'Your classes, tests, results and school life in one place.', actions: [['My subjects', BookOpen, 'See subjects for your current class.', 'academics', 'cyan'], ['Take a test', ClipboardCheck, 'Continue a published timed assessment.', 'test-runner', 'violet'], ['My report', Award, 'Grades, behavior and attendance report.', 'reports', 'emerald'], ['Digital ID & profile', QrCode, 'Your QR pass and photo-only profile edit.', 'profile', 'amber'], ['Homework', FileText, 'View work and due dates.', 'homework', 'rose'], ['School notices', MessageSquare, 'Announcements from the academy.', 'notices', 'cyan']] },
  parent: { title: 'Parent portal', description: 'A clear view of your child’s progress, wellbeing and school life.', actions: [['My children', Users, 'Profiles and class information.', 'students', 'cyan'], ['Fees & balances', CircleDollarSign, 'Invoices, payments and outstanding balances.', 'finance', 'amber'], ['Attendance', CalendarDays, 'Know when your child is present or late.', 'attendance', 'emerald'], ['Results & behavior', Award, 'Grades, reports and behavior notes.', 'reports', 'violet'], ['Transport', Bus, 'Route and pickup information.', 'transport', 'cyan'], ['Feeding', Utensils, 'School meal records.', 'feeding', 'rose']] },
  accountant: { title: 'Finance and operations workspace', description: 'Track money, assets, stock and transport with confidence.', actions: [['Fees & balances', CircleDollarSign, 'Invoices, payments and outstanding fees.', 'finance', 'amber'], ['Expenses & budgets', WalletCards, 'Income, expenses and budgets.', 'expenses', 'violet'], ['Inventory store', Package, 'Uniforms, books, stationery and equipment.', 'inventory', 'cyan'], ['Assets', School, 'Computers, desks, buildings and vehicles.', 'assets', 'emerald'], ['Transport', Bus, 'Buses, routes, drivers and students.', 'transport', 'rose']] },
  librarian: { title: 'Library workspace', description: 'Keep the catalogue accurate and every loan accountable.', actions: [['Book catalogue', Library, 'Add books, subjects, shelves and quantities.', 'library', 'cyan'], ['Active loans', ClipboardCheck, 'See who borrowed each book and due dates.', 'loans', 'amber'], ['Student lookup', Users, 'Find a student before issuing a book.', 'students', 'violet']] },
};

const roleStats = {
  dos: [['students', '150', 'School students', 'active records', 'blue'], ['teachers', '15', 'Teachers', 'managed staff', 'mint'], ['admissions', '08', 'Pending admissions', 'need review', 'violet']],
  teacher: [['students', '42', 'My students', 'assigned classes', 'blue'], ['attendance', '96%', 'Today attendance', 'your classes', 'mint'], ['academics', '06', 'Active assessments', 'this term', 'violet']],
  student: [['students', 'S3-A', 'My class', '2025 / 2026', 'blue'], ['attendance', '98%', 'My attendance', 'this term', 'mint'], ['academics', '08', 'My subjects', 'this term', 'violet']],
  parent: [['students', '02', 'My children', 'linked profiles', 'blue'], ['attendance', '96%', 'Attendance', 'this term', 'mint'], ['fees', '180K', 'Outstanding fees', 'RWF balance', 'amber']],
  accountant: [['fees', '8.42M', 'Fees collected', 'this term · RWF', 'amber'], ['students', '34', 'Outstanding accounts', 'need follow-up', 'violet'], ['inventory', '12', 'Low stock items', 'reorder soon', 'blue']],
  librarian: [['students', '150', 'Student borrowers', 'active students', 'blue'], ['library', '286', 'Books in catalogue', 'library collection', 'mint'], ['loans', '18', 'Active loans', 'due this week', 'amber']],
};

const tableConfig = {
  timetable: { endpoint: '/timetable', key: 'timetable', title: 'Timetable', columns: [{ key: 'dayOfWeek', label: 'Day' }, { key: 'startsAt', label: 'Start' }, { key: 'endsAt', label: 'End' }, { key: 'subjectName', label: 'Subject' }, { key: 'className', label: 'Class' }, { key: 'room', label: 'Room' }] },
  teachers: { endpoint: '/teachers', key: 'teachers', title: 'Teacher management', columns: [{ key: 'fullName', label: 'Teacher' }, { key: 'employeeNumber', label: 'Employee no.' }, { key: 'contractType', label: 'Contract' }, { key: 'phone', label: 'Phone' }, { key: 'isActive', label: 'Status' }] },
  reports: { key: 'grades', title: 'Student report', columns: [{ key: 'subject', label: 'Subject' }, { key: 'score', label: 'Score' }, { key: 'maxScore', label: 'Maximum' }] },
  homework: { endpoint: '/homework', key: 'homework', title: 'Homework', columns: [{ key: 'title', label: 'Title' }, { key: 'description', label: 'Description' }, { key: 'dueDate', label: 'Due date' }] },
  feeding: { endpoint: '/feeding/stock', key: 'stock', title: 'Feeding stock', columns: [{ key: 'itemName', label: 'Item' }, { key: 'quantity', label: 'Quantity' }, { key: 'unit', label: 'Unit' }, { key: 'reorderLevel', label: 'Reorder level' }] },
  expenses: { endpoint: '/finance/expenses', key: 'expenses', title: 'Expenses', columns: [{ key: 'category', label: 'Category' }, { key: 'description', label: 'Description' }, { key: 'amount', label: 'Amount' }, { key: 'spentAt', label: 'Date' }] },
  assets: { endpoint: '/assets', key: 'assets', title: 'Assets', columns: [{ key: 'name', label: 'Asset' }, { key: 'assetTag', label: 'Asset tag' }, { key: 'category', label: 'Category' }, { key: 'conditionStatus', label: 'Condition' }, { key: 'location', label: 'Location' }] },
  loans: { endpoint: '/library/loans', key: 'loans', title: 'Library loans', columns: [{ key: 'title', label: 'Book' }, { key: 'studentName', label: 'Student' }, { key: 'issuedAt', label: 'Issued' }, { key: 'dueAt', label: 'Due' }, { key: 'returnedAt', label: 'Returned' }] },
};

export default function RoleWorkspacePage({ role, user, t, onNavigate, initialPage }) {
  const copy = roleCopy[role] || roleCopy.student; const [selected, setSelected] = useState(tableConfig[initialPage] ? initialPage : null); const [rows, setRows] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const stats = roleStats[role] || roleStats.student;
  useEffect(() => { if (!selected || !tableConfig[selected]) return; let active = true; setLoading(true); setError(''); const item = tableConfig[selected]; const load = async () => { let endpoint = item.endpoint; if (selected === 'reports') { const studentId = await resolveStudentId(user); if (!studentId) throw new Error('No student record is available for reports.'); endpoint = `/students/${studentId}/report`; } const { data } = await api.get(endpoint); if (active) setRows(data[item.key] || []); }; load().catch((requestError) => active && setError(requestError.response?.data?.error || requestError.message || 'Connect the backend or add records to view this workspace.')).finally(() => active && setLoading(false)); return () => { active = false; }; }, [selected, user]);
  if (selected && tableConfig[selected]) { const item = tableConfig[selected]; return <div className="space-y-6"><button onClick={() => setSelected(null)} className="text-xs font-bold text-cyan-700">← Back to workspace</button><div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><h1 className="font-display text-2xl font-bold text-slate-800">{item.title}</h1><p className="mt-1 text-xs text-slate-500">Role-scoped operational view</p></div><button onClick={() => onNavigate('overview')} className="rounded-xl bg-cyan-700 px-4 py-3 text-xs font-bold text-white">Dashboard</button></div>{error && <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">{error}</div>}{loading ? <div className="rounded-2xl border border-slate-200 bg-white p-14 text-center text-xs text-slate-400">{t.loading}</div> : <DataTable columns={item.columns} rows={rows} emptyLabel={t.noData} />}</div>; }
  return <div className="space-y-7"><section className="rounded-3xl bg-[#17333d] p-6 text-white shadow-xl shadow-cyan-950/10 sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-teal-200">{t.app}</p><h1 className="mt-3 font-display text-2xl font-bold sm:text-3xl">{copy.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{copy.description}</p></div><ShieldCheck className="hidden text-teal-300 sm:block" size={28} /></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([kind, value, title, detail, tone]) => <StatCard key={title} kind={kind} title={title} value={value} note="Live" detail={detail} tone={tone} />)}</section><section><div className="mb-4"><h2 className="font-display text-sm font-bold text-slate-800">Quick access</h2><p className="mt-1 text-xs text-slate-400">Open the tools available for your role.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{copy.actions.map(([title, Icon, description, target, tone]) => <ActionCard key={title} icon={Icon} title={title} description={description} tone={tone} onClick={() => tableConfig[target] ? setSelected(target) : onNavigate(target)} />)}</div></section></div>;
}

async function resolveStudentId(user) {
  if (user?.role === 'student') { const { data } = await api.get('/student/profile'); return data.profile?.id; }
  if (user?.role === 'parent') { const { data } = await api.get('/parent/summary'); return data.children?.[0]?.id; }
  const { data } = await api.get('/students'); return data.students?.[0]?.id;
}
