import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, ShieldAlert } from 'lucide-react';
import api from '../lib/api';

export default function TestRunnerPage({ t, onBack }) {
  const [tests, setTests] = useState([]); const [selected, setSelected] = useState(null); const [questions, setQuestions] = useState([]); const [attempt, setAttempt] = useState(null); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState({}); const [seconds, setSeconds] = useState(0); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { api.get('/tests').then(({ data }) => setTests(data.tests || [])).catch((requestError) => setError(requestError.response?.data?.error || 'Unable to load tests.')); }, []);
  useEffect(() => { if (!attempt || seconds <= 0) return undefined; const timer = window.setInterval(() => setSeconds((value) => value - 1), 1000); return () => window.clearInterval(timer); }, [attempt, seconds]);
  useEffect(() => { if (attempt && seconds === 0) submit(); }, [seconds, attempt]);
  const start = async (test) => { setError(''); try { const [questionResponse, attemptResponse] = await Promise.all([api.get(`/tests/${test.id}/questions`), api.post(`/tests/${test.id}/attempts`)]); setSelected(test); setQuestions(questionResponse.data.questions || []); setAttempt(attemptResponse.data.attempt); setSeconds(Number(attemptResponse.data.attempt.durationMinutes || test.durationMinutes) * 60); setIndex(0); setAnswers({}); } catch (requestError) { setError(requestError.response?.data?.error || 'Unable to start this test.'); } };
  const submit = async () => { if (!attempt) return; try { const { data } = await api.post(`/test-attempts/${attempt.id}/submit`, { answers }); setMessage(`Test submitted. Score: ${data.score}`); setAttempt(null); } catch (requestError) { setError(requestError.response?.data?.error || 'Unable to submit test.'); } };
  const current = questions[index]; const minutes = String(Math.floor(seconds / 60)).padStart(2, '0'); const secs = String(seconds % 60).padStart(2, '0');
  if (!selected || !attempt) return <div className="space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={16} /> Dashboard</button><section className="rounded-3xl bg-[#17333d] p-6 text-white sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200">Student assessments</p><h1 className="mt-2 font-display text-2xl font-bold">Available tests</h1><p className="mt-2 text-sm text-slate-300">Questions appear one at a time. Copy and selection are disabled while testing.</p></section>{message && <div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-xs text-emerald-700"><CheckCircle2 size={16} />{message}</div>}{error && <div className="rounded-xl bg-rose-50 px-4 py-3 text-xs text-rose-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2">{tests.map((test) => <article key={test.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-display text-sm font-bold text-slate-800">{test.title}</h2><p className="mt-2 text-xs text-slate-500">{test.durationMinutes} minutes · {test.isPublished ? 'Published' : 'Not available'}</p><button disabled={!test.isPublished} onClick={() => start(test)} className="mt-5 rounded-xl bg-cyan-700 px-4 py-3 text-xs font-bold text-white disabled:bg-slate-200">Start test</button></article>)}</div></div>;
  return <div className="mx-auto max-w-3xl select-none space-y-5" onCopy={(event) => event.preventDefault()} onContextMenu={(event) => event.preventDefault()}><div className="flex items-center justify-between"><span className="text-xs font-bold text-cyan-700">{selected.title}</span><span className={`flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${seconds < 60 ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}><Clock3 size={15} />{minutes}:{secs}</span></div><div className="rounded-3xl bg-[#17333d] p-6 text-white sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-teal-200">Question {index + 1} of {questions.length}</p><h1 className="mt-4 font-display text-xl font-bold leading-8">{current.prompt}</h1></div><ShieldAlert className="text-teal-300" size={21} /></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{current.questionType === 'choice' ? <div className="space-y-3">{(current.options || []).map((option) => <label key={String(option)} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm hover:border-cyan-400"><input type="radio" name={`question-${current.id}`} checked={answers[String(current.id)] === option} onChange={() => setAnswers((value) => ({ ...value, [current.id]: option }))} />{option}</label>)}</div> : <input value={answers[String(current.id)] || ''} onChange={(event) => setAnswers((value) => ({ ...value, [current.id]: event.target.value }))} placeholder={current.questionType === 'match' ? 'Enter your matching answer' : 'Type your answer'} className="w-full rounded-xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-cyan-600" />}</div><div className="flex justify-between gap-3"><button disabled={index === 0} onClick={() => setIndex((value) => value - 1)} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-600 disabled:opacity-40"><ArrowLeft size={16} /> Back</button>{index < questions.length - 1 ? <button onClick={() => setIndex((value) => value + 1)} className="flex items-center gap-2 rounded-xl bg-cyan-700 px-4 py-3 text-xs font-bold text-white">Next <ArrowRight size={16} /></button> : <button onClick={submit} className="rounded-xl bg-emerald-600 px-4 py-3 text-xs font-bold text-white">Submit test</button>}</div></div>;
}
