import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Eye, FileCheck2, GripVertical, ShieldAlert } from 'lucide-react';
import api from '../lib/api';

export default function TestRunnerPage({ onBack }) {
    const [tests, setTests] = useState([]); const [selectedTest, setSelectedTest] = useState(null); const [questions, setQuestions] = useState([]); const [attempt, setAttempt] = useState(null); const [answers, setAnswers] = useState({}); const [index, setIndex] = useState(0); const [seconds, setSeconds] = useState(0); const [result, setResult] = useState(null); const [confirmSubmit, setConfirmSubmit] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [dragging, setDragging] = useState(null); const submitting = useRef(false);
    useEffect(() => { api.get('/tests').then(({ data }) => setTests(data.tests || [])).catch((err) => setError(err.response?.data?.error || 'Unable to load tests.')); }, []);
    useEffect(() => { if (!attempt || seconds <= 0) return undefined; const timer = window.setInterval(() => setSeconds((value) => value - 1), 1000); return () => window.clearInterval(timer); }, [attempt, seconds]);
    useEffect(() => { if (attempt && seconds === 0 && !submitting.current) submit(); }, [seconds, attempt]);
    const start = async (test) => { setError(''); setMessage(''); try { const [questionsResponse, attemptResponse] = await Promise.all([api.get(`/tests/${test.id}/questions`), api.post(`/tests/${test.id}/attempts`)]); const nextAttempt = attemptResponse.data.attempt; if (nextAttempt.status && nextAttempt.status !== 'in_progress') { setMessage(`You already submitted this test. Score: ${nextAttempt.score ?? 0}`); return; } setSelectedTest(test); setQuestions(questionsResponse.data.questions || []); setAttempt(nextAttempt); setAnswers({}); setIndex(0); setSeconds(Number(nextAttempt.durationMinutes || test.durationMinutes) * 60); submitting.current = false; } catch (err) { setError(err.response?.data?.error || 'Unable to start this test.'); } };
    const submit = async () => { if (!attempt || submitting.current) return; submitting.current = true; try { const { data } = await api.post(`/test-attempts/${attempt.id}/submit`, { answers }); setResult(data); setAttempt(null); setConfirmSubmit(false); } catch (err) { setError(err.response?.data?.error || 'Unable to submit test.'); submitting.current = false; } };
    const setAnswer = (value) => setAnswers((current) => ({ ...current, [questions[index].id]: value }));
    const current = questions[index]; const grouped = tests.reduce((groups, test) => { const key = test.subjectName || 'Other subjects'; groups[key] = [...(groups[key] || []), test]; return groups; }, {});
    if (result) return <ResultView test={selectedTest} result={result} questions={questions} onBack={() => { setResult(null); setSelectedTest(null); }} />;
    if (!selectedTest || !attempt) return <div className="space-y-6"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={16} /> Dashboard</button><section className="rounded-3xl bg-[#17333d] p-6 text-white sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-teal-200">Student assessments</p><h1 className="mt-2 font-display text-2xl font-bold">Tests by subject</h1></section>{message && <Notice tone="success">{message}</Notice>}{error && <Notice tone="error">{error}</Notice>}{Object.keys(grouped).map((subject) => <section key={subject} className="space-y-3"><h2 className="flex items-center gap-2 font-display text-lg font-bold text-slate-800"><FileCheck2 size={19} className="text-cyan-700" />{subject}</h2><div className="grid gap-4 md:grid-cols-2">{grouped[subject].map((test) => <article key={test.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-display text-sm font-bold text-slate-800">{test.title}</h3><p className="mt-2 text-xs text-slate-500">{test.className} · {test.durationMinutes} minutes</p><button onClick={() => setSelectedTest(selectedTest?.id === test.id ? null : test)} className="mt-5 flex items-center gap-2 text-xs font-bold text-cyan-700"><Eye size={15} /> View uploaded test</button>{selectedTest?.id === test.id && <div className="mt-4 rounded-xl bg-cyan-50 p-4"><p className="text-xs leading-5 text-slate-600">You are allowed to perform this test in {test.durationMinutes} minutes.</p><div className="mt-4 flex gap-2"><button onClick={() => setSelectedTest(null)} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-600">Cancel</button><button onClick={() => start(test)} className="rounded-xl bg-cyan-700 px-4 py-2 text-xs font-bold text-white">Start</button></div></div>}</article>)}</div></section>)}</div>;
    return <div className="mx-auto max-w-3xl select-none space-y-5" onCopy={(event) => event.preventDefault()} onContextMenu={(event) => event.preventDefault()}><div className="flex items-center justify-between"><span className="text-xs font-bold text-cyan-700">{selectedTest.title}</span><span className="flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><Clock3 size={15} />{String(Math.floor(seconds / 60)).padStart(2, '0')}:{String(seconds % 60).padStart(2, '0')}</span></div><div className="rounded-3xl bg-[#17333d] p-6 text-white sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-teal-200">Question {index + 1} of {questions.length}</p><h1 className="mt-4 font-display text-xl font-bold leading-8">{current.prompt}</h1></div><QuestionAnswer question={current} value={answers[current.id]} onChange={setAnswer} dragging={dragging} setDragging={setDragging} /><div className="flex justify-between gap-3"><button disabled={index === 0} onClick={() => setIndex((value) => value - 1)} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-xs font-bold text-slate-700 disabled:opacity-40"><ArrowLeft size={15} /> Previous</button>{index < questions.length - 1 ? <button onClick={() => setIndex((value) => value + 1)} className="flex items-center gap-2 rounded-xl bg-cyan-700 px-4 py-3 text-xs font-bold text-white">Next <ArrowRight size={15} /></button> : <button onClick={() => setConfirmSubmit(true)} className="rounded-xl bg-emerald-700 px-4 py-3 text-xs font-bold text-white">Submit</button>}</div>{confirmSubmit && <Confirm title="Are you complete? Do you want to submit the test?" onCancel={() => setConfirmSubmit(false)} onConfirm={submit} />}</div>;
}

function QuestionAnswer({ question, value, onChange, dragging, setDragging }) {
    const options = Array.isArray(question.options) ? question.options : []; const current = Array.isArray(value) ? value : [];
    if (question.questionType === 'choice') return <div className="rounded-2xl border border-slate-200 bg-white p-5">{options.map((option) => <label key={String(option)} className="mb-3 flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm"><input type="radio" checked={value === option} onChange={() => onChange(option)} />{option}</label>)}</div>;
    if (question.questionType === 'fill') return <div className="rounded-2xl border border-slate-200 bg-white p-5"><input value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder="Type the missing answer" className="w-full rounded-xl border border-slate-200 px-4 py-4 text-sm outline-none focus:border-cyan-600" /></div>;
    if (question.questionType === 'match') return <div className="space-y-2 rounded-2xl border border-slate-200 bg-white p-5">{options.map((left, itemIndex) => <label key={String(left)} className="flex items-center gap-3 text-sm"><span className="flex-1 rounded-xl bg-slate-50 p-3">{left}</span><select value={current[itemIndex] || ''} onChange={(event) => { const next = [...current]; next[itemIndex] = event.target.value; onChange(next); }} className="flex-1 rounded-xl border border-slate-200 p-3"><option value="">Select match</option>{options.map((right) => <option key={String(right)} value={right}>{right}</option>)}</select></label>)}</div>;
    if (question.questionType === 'rearrange' || question.questionType === 'drag') { const items = current.length ? current : options; return <div className="space-y-2 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold text-slate-500">Arrange items in the correct order</p>{items.map((item, itemIndex) => <div key={`${item}-${itemIndex}`} draggable={question.questionType === 'drag'} onDragStart={() => setDragging(itemIndex)} onDragOver={(event) => event.preventDefault()} onDrop={() => { const next = [...items]; const [moved] = next.splice(dragging, 1); next.splice(itemIndex, 0, moved); onChange(next); setDragging(null); }} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm"><GripVertical size={16} className="text-slate-400" /><span>{item}</span><span className="ml-auto text-xs text-slate-400">{itemIndex + 1}</span></div>)}</div>; }
    return null;
}
function Confirm({ title, onCancel, onConfirm }) { return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-bold text-amber-900">{title}</p><div className="mt-3 flex gap-2"><button onClick={onCancel} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-700">Cancel</button><button onClick={onConfirm} className="rounded-xl bg-rose-700 px-4 py-2 text-xs font-bold text-white">OK</button></div></div>; }
function Notice({ tone, children }) { return <div className={`rounded-xl px-4 py-3 text-xs ${tone === 'error' ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700'}`}>{children}</div>; }
function ResultView({ test, result, questions, onBack }) { return <div className="mx-auto max-w-3xl space-y-5"><button onClick={onBack} className="flex items-center gap-2 text-xs font-bold text-cyan-700"><ArrowLeft size={16} /> Available tests</button><section className="rounded-3xl bg-[#17333d] p-6 text-white"><p className="text-xs text-teal-200">{test?.title}</p><h1 className="mt-2 font-display text-3xl font-bold">Score: {result.score} / {result.maxScore ?? result.score}</h1><p className="mt-2 text-sm font-bold text-teal-200">{result.percentage ?? 0}%</p></section><div className="space-y-3">{(result.breakdown || []).map((item, itemIndex) => <div key={item.questionId} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-500">Question {itemIndex + 1}</p><p className="mt-1 text-sm text-slate-800">{questions[itemIndex]?.prompt}</p><p className={`mt-2 text-xs font-bold ${item.correct ? 'text-emerald-700' : 'text-rose-700'}`}>{item.correct ? 'Correct' : 'Incorrect'} · Your answer: {String(item.actual ?? 'No answer')}</p>{!item.correct && <p className="mt-1 text-xs text-slate-500">Expected: {String(item.expected)}</p>}</div>)}</div></div>; }
